# Homework 6: NumPy(29 pts)

name: Bryant Willoughby 

email: btwillou@umich.edu

This homework assignment took me 5 hours in total to complete. (Please help us to gauge the difficulty of the assignment.)

## Collaboration Disclosure

In the cell below, please list *everyone* with whom you discussed any of the homework problems, excluding only the GSIs and the course instructor. 

If you did not discuss the homework with anyone else, write __"I did not discuss this homework with anyone."__

Even if you discuss questions with other, the code you submit must be only yours. All work is checked with the [MOSS plagiarism detector](https://theory.stanford.edu/~aiken/moss/).

---

## Submission Instructions
Your homework solutions should be written entirely in this Jupyter notebook file. Once it contains your solutions, you should submit this notebook through Canvas. 


Before submitting, please make sure to __Cells->Run All__ executes without errors; errors in your code translate directly to point deductions. 
In general, you don't need to do explicitly raise errors (e.g. with the ```raise``` function) if we don't ask you to in the problem statement.
However, even in cases where we ask you to check for errors, your submission should not contain any examples of your functions actually raising those errors.

Note that many parts of this homework where you are expected to type in code will have ```NotImplementedError()``` as a placeholder. You need to delete this function and replace it with your own code.

## Homework tips 

1. **Start early!** If you run into trouble installing things or importing packages, it’s
best to find those problems well in advance, not the night before your assignment is
due when we cannot help you!

2. **Make sure you back up your work!** At a minimum, do your work in a Dropbox
folder. Better yet, use git, which is well worth your time and effort to learn.

3. **Be careful to follow directions!** Remember that Python is case sensitive. If
you are ask you to define a function called my_function and you define a function
called My_Function, you will not receive full credit. You may want to copy-paste
the function names below to make sure that the functions in your notebook match.

## Error checking

You do not need to do error checking (raising errors, etc.) in your code unless we explicitly ask you to so in a problem.


## Nbgrader

We will be using `nbgrader` to grade your jupyter notebook. You will notice some `read-only` cells in the assignment that contain `assert` statements. These are tests that your code must pass for your solution to be correct. If any of the tests fail, you will get an python error and not get points for that question. 

**Note:** The tests shown not are not comprehensive; additional tests will be used at grading time. You are encouraged to read the problem carefully and verify your code covers all possible cases.

**Be careful:** If a jupyter notebook cell takes longer than `60s` to run, the autograder will not grade it and you will receive zero credit for that question.

## Question 1:. The Bakersville Bake-off! (3 pts)

The houses in the town of Bakersville are arranged on a grid with R rows (numbered 1 through R) and C columns (numbered 1 through C). The house located on row r and on column c is denoted by (r, c). We say two houses are **neighbors** if they have a common side. 

During the annual Bakersville Bake-off, each household bakes a certain number of cakes to share with their neighbors.
The town comptroller keeps track in an $R \times C$ matrix $A$, where $A_{r, c}$ is the number of cakes which household $(r, c)$ has baked.

The stability of the social order in Bakersville depends on each house baking enough cakes so they can give at least one cake to each neighbor and submit one cake to be judged. Thus, we say a house is **stable** if the number of cakes $A_{r, c}$ is strictly greater than its number of neigbors. We say Bakersville is **stable** if every house is stable. 

The comptroller has asked you to define a function `is_stable` that takes an $R \times C$ numpy array (i.e., an ndarray) as its only argument and returns a Python Boolean that is True if and only if the argument is a stable array and False otherwise. 

In [1]:
import numpy as np
def is_stable(A):
    """Return True iff every house has more cakes than its number of grid neighbors."""
    if not isinstance(A, np.ndarray) or A.ndim != 2:
        return False
    R, C = A.shape
    r = np.arange(R)[:, None] # shape: (R,1): [[0], [1], ..., [R-1]]
    c = np.arange(C)[None, :] # shape: (1,C): [[0, 1, ..., C-1]]

    # broadcasted comparisons to count neighbors
    up    = (r > 0).astype(int)
    down  = (r < R - 1).astype(int)
    left  = (c > 0).astype(int)
    right = (c < C - 1).astype(int)

    # sum the neighbor counts
    neighbors = up + down + left + right
    return bool(np.all(A > neighbors))

# array1 = np.array([4, 7, 8,
#                    5, 10, 9,
#                    3, 5, 7]).reshape(3, 3)
# R, C = array1.shape
# r = np.arange(R)[:,None]; print(r)
# c = np.arange(C)[None, :]; print(c)

# up    = (r > 0).astype(int)
# down  = (r < R - 1).astype(int)
# left  = (c > 0).astype(int)
# right = (c < C - 1).astype(int)

# neighbors = up + down + left + right; print(neighbors)
# bool(np.all(array1 > neighbors))

In [29]:
# import numpy as np

# def is_stable(A):
#     """Return True iff every house has more cakes than its number of grid neighbors.

#     A must be a 2D NumPy array (R x C). Neighbors are 4-connected (up, down, left, right).
#     """
#     if not isinstance(A, np.ndarray) or A.ndim != 2:
#         return False
#     R, C = A.shape
#     neighbors = np.full((R, C), 4, dtype=int)
#     neighbors[0, :] -= 1
#     neighbors[-1, :] -= 1
#     neighbors[:, 0] -= 1
#     neighbors[:, -1] -= 1
#     return bool(np.all(A > neighbors))

# array1 = np.array([4, 7, 8,
#                    5, 10, 9,
#                    3, 5, 7]).reshape(3, 3)
# array1.shape
# neighbors = np.full((3,3), 4); print(neighbors)
# neighbors[0, :] -= 1; print(neighbors)
# neighbors[-1, :] -= 1; print(neighbors)
# neighbors[:, 0] -= 1; print(neighbors)
# neighbors[:, -1] -= 1; print(neighbors)
# np.all(array1 > neighbors)
# bool(np.all(array1 > neighbors))

In [2]:
array1 = np.array([4, 7, 8,
                   5, 10, 9,
                   3, 5, 7]).reshape(3, 3)
array2 = np.array([3, 2, 4,
                   1, 1, 2,
                   3, 3, 3]).reshape(3, 3)


assert is_stable(array1)
assert not is_stable(array2)
assert not is_stable(np.array([1., 0., 1.]))

## Question 2: Down with `for` loops (12 pts)
Each of the problems below contains a function that uses `for` loops to perform a certain operation on arrays. Your job is to re-write these function using only Numpy array manipulations and library functions (e.g. `np.xxx()`). Do not use any `for` or `while` loops, iterators, generators, or list comprehensions in your solutions.

**2(a)**  Return all of the rows of the 2-D integer matrix `A` where where each entry of the row is distinct (3 pts)

In [3]:
def distinct_rows_py(A):
    'Return all rows of A that have completely distinct entries.'
    # set builds unordered collection of unique elements
    return np.array([a for a in A if len(set(a)) == len(a)])
A = np.eye(5)
print(distinct_rows_py(A))
B = np.arange(9).reshape(3, 3)
print(distinct_rows_py(B))

# A = np.eye(5)
# for a in A:
#     print(set(a))
#     print(len(a))
#     print(len(set(a)))

[]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
def distinct_rows_np(A):
    """Return rows of A whose entries are all distinct (no duplicates within a row)."""
    if A.size == 0:
        # Keep 2D shape with 0 rows and same number of columns
        return A.reshape(0, A.shape[1])

    # Sort each row so any duplicates become adjacent
    sr = np.sort(A, axis=1)

    # Adjacent differences within each row; shape: (n_rows, n_cols-1)
    # If a row has a duplicate, the difference for that adjacent pair is 0
    diffs = np.diff(sr, axis=1)

    # Row is valid if all adjacent diffs are non-zero (i.e., no equal neighbors)
    no_adj_equal = np.all(diffs != 0, axis=1)

    # Use the boolean mask to select only rows with all distinct entries
    return A[no_adj_equal]

# B = np.array([[3,2,1,5], 
#              [0,4,5,6], 
#              [1,1,2,1]]); print(B)
# sr = np.sort(B, axis = 1); print(sr)
# print(np.diff(sr, axis=1) != 0)
# no_adj_equal = np.all(np.diff(sr, axis=1) != 0, axis=1); print(no_adj_equal)
# B[no_adj_equal]

In [33]:
# def distinct_rows_np(A):
#     """Return rows of A whose entries are all distinct (no duplicates within a row)."""
#     # empty-input guard to preserve shape 
#     if A.size == 0:
#         return A.reshape(0, A.shape[1])
#     # row duplicates adjacent when sorted
#     sorted_rows = np.sort(A, axis=1) # row-wise sort
#     # marks where adjacent entries are equal
#     has_dupe = np.any(sorted_rows[:, 1:] == sorted_rows[:, :-1], axis=1)
#     keep = np.logical_not(has_dupe)  
#     return A[keep]

# A = np.empty([0,5]); print(A.shape)
# A = A.reshape(0, A.shape[1]); print(A.shape)
# B = np.array([[3,2,1,5], 
#              [0,4,5,5], 
#              [1,1,2,1]]); print(B)
# sorted_rows = np.sort(B, axis=1); print(sorted_rows)
# print(sorted_rows[:, 1:])
# print(sorted_rows[:, :-1])
# has_dupe = np.any(sorted_rows[:, 1:] == sorted_rows[:, :-1], axis=1); print(has_dupe)
# keep = np.logical_not(has_dupe); print(keep)
# B[keep]


In [5]:
A = np.eye(5)
np.testing.assert_allclose(distinct_rows_np(A), np.empty([0, 5]))

**2(b)** Given a vector $v$ of length $n$, and an integer $0<k<=n$, return a 2D array as: (3 pts)
```
[[v[0], ..., v[k-1]],
 [v[1], ..., v[k]  ],
 [v[2], ..., v[k+1]],
 [ .     .       . ],
 [ .     .       . ],
 [ .     .       . ],
 [v[n-k+1, ..., v[n]]
 ```

In [6]:
def sliding_stack_py(v, k):
    "Stack sliding windows of v of length k."
    rows = []
    for i in range(len(v) - k + 1):
        rows.append(v[i : (i + k)]) #pushses slice to end of rows
    return np.array(rows)
sliding_stack_py(np.array([1, 2, 3, 4, 5]), 3)

# v = np.array([1, 2, 3, 4, 5]); print(v)
# rows = []; k = 3
# for i in range(len(v) - k + 1): 
#     rows.append(v[i : (i + k)])
#     print(np.array(rows))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [7]:
import numpy as np

def sliding_stack_np(v, k):
    """Stack sliding windows of v (1D) with window length k using broadcasting."""
    n = v.shape[0]
    idx = np.arange(n - k + 1)[:, None] + np.arange(k)[None, :]
    return v[idx]

# v = np.array([1, 2, 3, 4, 5]); print(v)
# n = v.shape[0]; print(n)
# print(np.arange(n - 3 + 1))
# print(np.arange(n - 3 + 1)[:, None]) # shape (3, 1)
# print(np.arange(3)[None, :]) # shape (1, 3)
# idx = np.arange(n - 3 + 1)[:, None] + np.arange(3)[None, :]; print(idx)
# v[idx]

In [8]:
np.testing.assert_allclose(sliding_stack_np(np.array([1, 2, 3, 4, 5]), 3), np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5]]))
np.testing.assert_allclose(sliding_stack_np(np.array([1, 2, 3, 4, 5]), 5), np.array([[1, 2, 3, 4, 5]]))

**2(c)** Given a vector of non-negative integers `v`, with `max(v) = m`, return a vector `c` of length `m + 1` such that `c[i]` is the number of times that the integer `i` appears in `v`.(3 pts)

In [9]:
def digit_count_py(v):
    m = max(v)
    ret = np.zeros(m + 1, int)
    for vv in v:
        ret[vv] += 1
    return ret
v = np.array([0, 0, 1, 1, 2, 2, 2, 3, 5])
digit_count_py(v)

# print(v)
# m = max(v); print(m)
# ret = np.zeros(m + 1, int); print(ret)
# print("--------For loop--------")
# for vv in v: 
#     print(vv)
#     ret[vv] += 1
#     print(ret)

array([2, 2, 3, 1, 0, 1])

In [10]:
import numpy as np

def digit_count_np(v):
    """Count occurrences of integers 0..max(v) using vectorized broadcasting."""
    m = int(np.max(v))
    vals = np.arange(m + 1)
    return np.sum(v[:, None] == vals[None, :], axis=0)

digit_count_np(v)

# print(v)
# m = int(np.max(v)); print(m)
# vals = np.arange(m + 1); print(vals)
# print(v[:, None]) # shape: (n,1)
# print(vals[None, :]) # shape: (1, m+1)
# print(v[:, None] == vals[None, :]) # shape: (n, m+1)
# np.sum(v[:, None] == vals[None, :], axis=0)

array([2, 2, 3, 1, 0, 1])

In [11]:
v = np.array([0, 0, 1, 1, 2, 2, 2, 3, 4])
np.testing.assert_allclose(digit_count_np(v), np.array([2, 2, 3, 1, 1]))
v = np.array([0, 0, 0, 0, 2, 2, 2, 3, 4])
np.testing.assert_allclose(digit_count_np(v), np.array([4, 0, 3, 1, 1]))

**2(d)** Call a square $n\times n$ matrix $A$ *countersymmetric* if $A_{ij} = A_{n-j,n-i}$ for all $i$ and $j$. An example of such a matrix is:

$$
\begin{pmatrix}
4 & 3 & 2 & 1 & 0\\
8 & 7 & 6 & 5 & 1\\
11 & 10 & 9 & 6 & 2\\
13 & 12 & 10 & 7 & 3\\
14 & 13 & 11 & 8 & 4
\end{pmatrix}
$$


Write a function `is_countersym` that checks this property: (3 pts)

Note: Using 0-based indexing (as Python does), a square matrix $(A \in \mathbb{R}^{n\times n})$ is countersymmetric if

$$
A_{i,j} \;=\; A_{\,n+1-j,\;n+1-i}\quad\text{for } i,j \in \{1,\dots,n\}.
$$

In [12]:
def is_countersym_py(A):
    "Returns True if A is countersymmetric"
    n = A.shape[0]
    for i in range(n):
        for j in range(n):
            if A[i, j] != A[n - j - 1, n - i - 1]:
                return False
    return True
cs_matrix = np.array([[ 4,  3,  2,  1,  0], [ 8,  7,  6,  5,  1], [11, 10,  9,  6,  2], [13, 12, 10,  7,  3], [14, 13, 11,  8,  4]])
print(is_countersym_py(cs_matrix))

True


In [13]:
import numpy as np

def is_countersym_np(A):
    """Return True if A is countersymmetric: A[i,j] == A[n-1-j, n-1-i]."""
    # flip both axes: rows and cols; then transpose
    flipped = A[::-1, ::-1].T
    # check elementwise equality
    return bool(np.all(A == flipped))

# print(cs_matrix)
# print(cs_matrix[::-1, ::-1])
# print(cs_matrix[::-1, ::-1].T)

In [14]:
cs_matrix = np.array([[ 4,  3,  2,  1,  0], [ 8,  7,  6,  5,  1], [11, 10,  9,  6,  2], [13, 12, 10,  7,  3], [14, 13, 11,  8,  4]])
assert is_countersym_np(cs_matrix), "The matrix is not counter-symmetric"


## Question 3: $k$-means clustering (14 pts)

$k$-means is a fundamental algorithm for clustering multivariate data. The inputs to the algorithm are:
- An $n\times p$ data matrix $X$ consisting of $n$ observations of a $p$-dimensional feature vector, and
- A $k\times p$ matrix $C$ containing initial guesses for each $k$ cluster centers.

The algorithm proceeds by iteratively a) assigning each point to the nearest cluster center, and b) recomputing the cluster centers as the mean of all of the currently assigned points. Here is a partial implementation:

In [16]:
def kmeans(X, C):
    """
    K-means algorithm.

    Args:
        - X: ndarray, shape (n, p), n observations of p-dimensional feature vector
        - C: ndarray, shape (k, p), k initial cluster centers

    Returns:
        Tuple of length two:
        The first entry is integer ndarray, shape (n), cluster assignments for each data point
        The second entry is ndarray, shape (k, p), centers of each cluster
    """
    assert X.shape[1] == C.shape[1]  # p should match
    old_assignments = None
    while True:
        assignments = nearest_cluster(X, C)
        if np.all(assignments == old_assignments):
            # converged
            return assignments, C
        old_assignments = assignments
        C = compute_centroids(X, assignments)

You will finish implementing this algorithm by completing the missing functions `nearest_cluster()` and `compute_centroids()` below. Note: as in the Question 1, avoid using loops, iterators, or comprehensions. You can find solutions with only broadcasting

**3(a)** Implement the function `nearest_cluster`. It should take two array arguments, the data points `X` and the cluster centers `C`, and return an integer array giving the index in `C` which is nearest to each point in `X`. (3 pts)

In [17]:
def nearest_cluster(X, C):
    """
    For each point in X, find the nearest point in C.

    Args:
        X: ndarray, shape (n, p), n points of dimension p.
        C: ndarray, shape (k, p), k points of dimension p.

    Returns:
        Integer array of length n, [j[1], j[2], ..., j[n]], such that |X[i] - C[j[i]]| <= |X[i] - C[ell]| for 1 <= ell <= k
    """
    # X[:,None,:]: shape (n,1,p); C[None,:,:]: shape (1,k,p)
        # subtraction broadcasts to shape (n,k,p)
        # all n - k pairwise diffs across p features, i.e. axis=2
    dists = np.linalg.norm(X[:, None, :] - C[None, :, :], axis=2) # (n, k)
    # return index of min dist (row-wise) for each of n points
    return np.argmin(dists, axis=1)

# X = np.array([[-1], [0.5], [1], [1.3], [1.6], [2], [2.3], [2.7], [3], [100]])
# print(X); print(X.shape)
# C = np.array([[1], [2], [3]])
# print(C); print(C.shape)
# dists = np.linalg.norm(X[:, None, :] - C[None, :, :], axis=2); print(dists)
# a = np.argmin(dists, axis=1); print(a)

In [18]:
ans = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])
X = np.array([[-1], [0.5], [1], [1.3], [1.6], [2], [2.3], [2.7], [3], [100]])
C = np.array([[1], [2], [3]])
np.testing.assert_allclose(nearest_cluster(X, C), ans)

X = np.array([[-101, 1], [1,1], [1, 1.01], [1.5, 1.6], [2.5, -3], [2.5, 2.7], [3, 33]])
C = np.array([[1, 1], [2,2], [3,3]])
ans = np.array([0, 0, 0, 1, 0, 2, 2])
np.testing.assert_allclose(nearest_cluster(X, C), ans)

**3(b)** Implement the function `compute_centroids`. It should take two array arguments, the data points `X` and the assignment array `a`, and return an $k \times p$ array containing the cluster centroids (averages) for each point assigned to cluster $0, \dots, k-1$. (You may assume that every entry of $a$ is between $0$ and $k-1$, inclusive.) (3 pts) 

In [19]:
def compute_centroids(X, a):
    """
    Compute cluster centroids: for labels a in [0..k-1], return k x p means.
    
    Args:
        X: ndarray, shape (n, p), n points of dimension p.
        a: integer ndarray, shape (n,), cluster assignment indices for each point in X
    
    Returns: 
        ndarray, shape (k, p), where row j is the mean of points in X assigned to cluster j
    
    """
    # infer number of clusters k from max label in a
    k = int(np.max(a)) + 1
    # one-hot encode assignments: shape (n, k)
        # one_hot[i, j] = 1 if a[i] == j else 0
    one_hot = (a[:, None] == np.arange(k)[None, :]).astype(float)
    # sum of points per cluster: (k, n) @ (n, p) = (k, p)
    sums = one_hot.T @ X
    # count of points per cluster: shape (k, 1) 
    counts = one_hot.sum(axis=0)[:, None]
    # centroids = mean per cluster (broadcast division over features): shape (k, p)
    return sums / counts

# print(X); print(X.shape)
# print(C); print(C.shape)
# print(a); print(a.shape)
# k = int(np.max(a)) + 1; print(k)
# print(a[:, None].shape); print(np.arange(k)[None, :].shape)
# one_hot = (a[:, None] == np.arange(k)[None, :]).astype(float); print(one_hot)
# sums = one_hot.T @ X; print(sums)
# counts = one_hot.sum(axis=0)[:, None]; print(counts)
# print(sums / counts)

In [20]:
import numpy as np
np.random.seed(1)
X = np.random.rand(30, 2)
a = np.random.randint(0, 5, size=30)
assert compute_centroids(X, a).shape == (5, 2)
assert np.allclose(X[a == 0].mean(axis=0), compute_centroids(X, a)[0])

**3(c)** The performance of the $k$-means algorithm is known to depend heavily on the starting point (the initial clusters `C` passed in as the second argument.) In some cases, using a "good" starting point can dramatically improve the performance of the algorithm.

The $k$-means++ algorithm is designed to find such a good starting point. [According to Wikipedia](https://en.wikipedia.org/wiki/K-means%2B%2B), the steps of $k$-means++ are:

1. Choose one center uniformly at random among the data points.
2. For each data point $x$ not chosen yet, compute $D(x)$, the distance between $x$ and the nearest center that has already been chosen.
3. Choose one new data point at random as a new center, using a weighted probability distribution where a point $x$ is chosen with probability proportional to $D(x)^2$.
4. Repeat Steps 2 and 3 until $k$ centers have been chosen.

Implement this algorithm using the skeleton provided below. As before, your implementation should only use Numpy functions--no additional loops or comprehensions. 

**Note**: To ensure reproducibility, the parts of the algorithm that rely on ranndomness are provided for you. Your job is to fill in the missing lines necessary to complete the algoritm. (5 pts.)

In [21]:
def kmeanspp(X, k, rng):
    """
    k-means++ algorithm.

    Args:
        - X: ndarray, shape (n, p), as above.
        - k, the number of clusters.
        - rng: instance of np.random.Generator().

    Returns:
        ndarray, shape (k, p), cluster centers.
    """
    n, p = X.shape
    C = np.zeros((k, p))
    # step 1
    j = rng.choice(n)
    C[0] = X[j]
    for i in range(1, k):
        # step 2: D(x) = distance from each point to its nearest chosen center
        # pairwise distances between all points and current centers -> (n, i, p)
        pairwise = X[:, None, :] - C[None, :i, :]
        # Euclidean norms over features -> (n, i)
        dists = np.linalg.norm(pairwise, axis=2)
        #nearest-center distance per point -> (n,)
        D = np.min(dists, axis=1)
        # probabilities proportional to D(x)^2
        w = (D ** 2)
        w = w / np.sum(w) # normalize to sum to 1
        # step 3
        j = rng.choice(n, p=w)
        C[i] = X[j]
    return C

In [22]:
import numpy as np

np.random.seed(1)
X = np.random.rand(30, 4)
k = 2
rng = np.random.default_rng(12345)
assert kmeanspp(X, k, rng).shape == (2, 4)
ans = np.array([[0.87638915, 0.89460666, 0.08504421, 0.03905478], 
                [0.6634415 , 0.62169572, 0.11474597, 0.94948926]])
np.testing.assert_allclose(kmeanspp(X, k, rng), ans)

**3(d)** In order to measure how good a clustering is, we can define the *within-class variance* 

$$ V(\mathbf{X}, \mathbf{a}, \mathbf{C}) = \sum_{i=1}^n \| \mathbf{x}_i - \mathbf{c}_{a_i} \|^2,$$

where the $i$-th element of $\mathbf{a}=\{a_1,\dots,a_n\}$ is the cluster assignment of observation $i$, and $\mathbf{C}=(\mathbf{c}_1,\dots,\mathbf{c}_k)$ are the centers of each cluster. Thus, $V(\mathbf{X}, \mathbf{a}, \mathbf{C})$ is the sum of the squared distance from each data point to the center of its assigned cluster.

Implement this function. (Again, no loops, just use Numpy functions.) (3 pts) 

In [23]:
def V(X, a, C):
    """Within-class variance: sum_i ||X[i] - C[a[i]]||^2."""
    diffs = X - C[a] # gather assigned centroids and subtract from X
    return float(np.sum(diffs * diffs))

# X = np.arange(9).reshape(3, 3); print(X)
# a = np.arange(3); print(a)
# C = 2 + X; print(C)
# print(C[a]); print(C[a].shape)
# diffs = X - C[a]; print(diffs)
# np.sum(diffs * diffs)

In [24]:
import numpy as np

X = np.arange(9).reshape(3, 3)
a = np.arange(3)
C = 2 + X
np.testing.assert_allclose(V(X, a, C), 36)
