### Week 7 SciPy

In [1]:
import numpy as np

### Problem 1
In this exercise, you will use SciPy's optimization to find the minimum of a given function. You'll learn how to import the necessary modules from SciPy, define a function to optimize, and use SciPy's minimize function to find the optimal solution.

1) Import the required module from SciPy for optimization.

2) Define the following quadratic function: $f(x) = 2x^2 + 4x - 6$


4) Use SciPy's optimization function to find the minimum of this function. ($x$ and $f(x)$). Note I have named a variable name `result`, you might want to use the same name.  


*Hint*: Use scipy's `optimize.minimize` function. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html


In [12]:
from scipy import optimize 
# help(optimize.minimize)

In [15]:
def f(x):
    return 2 * x * x + 4 * x - 6

print("----Function Evaluated at x=3----\n")
print(f(3))  # Example usage

# minimize expects a scalar objective; wrap f to accept the optimizer's array input
    # fun: callable; Rather than passing f0 as the callable, wrap it to accept only x
    # x0: ndarray, shape (n,); Initial guess

result = optimize.minimize(lambda x: float(f(x[0])), x0=[0.0])
print("----Optimization Result----")
print(result)

----Function Evaluated at x=3----

24
----Optimization Result----
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -8.0
        x: [-1.000e+00]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 2.500e-01]]
     nfev: 6
     njev: 3


In [20]:
print(type(result))
print(type(result.x))
print(result)
print(f"Minimum found at x = {result.x[0]:.2f}, f(x) = {result.fun}")

<class 'scipy.optimize._optimize.OptimizeResult'>
<class 'numpy.ndarray'>
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -8.0
        x: [-1.000e+00]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 2.500e-01]]
     nfev: 6
     njev: 3
Minimum found at x = -1.00, f(x) = -8.0


### Problem 1.2
What if I want to keep x within the range of [0.5, 1.5]. Can you resolve the problem?

In [21]:
# bounds: sequence or scipy.optimize.Bounds, optional
    # Bounds on variables for constrained optimization
result = optimize.minimize(lambda x: float(f(x[0])), x0=[0.0], bounds=[(0.5,1.5)])
print(f"New Minimum found at x = {result.x[0]:.2f}, f(x) = {f(result.x[0]):.2f}")

New Minimum found at x = 0.50, f(x) = -3.50


### Additional Practice 

In [32]:
# SciPy as Scientific Python 


#How to use SciPy: Importing 
print("---------Making use of namespaces---------")
import numpy as np
my_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]); print(my_matrix)
from scipy.linalg import eigvals; print(eigvals(my_matrix))
from scipy import special, linalg; print(eigvals(my_matrix))
import scipy; print(scipy.linalg.eigvals(my_matrix))

#SciPy Linear Algebra 
print("\n---------SciPy Linear Algebra---------")
import scipy.linalg as spla; import numpy.linalg as npla; import time 
n = 1000
A = np.random.rand(n,n); b = np.random.rand(n)

start_time = time.time()
x_np = npla.solve(A, b) #matrix inverse 
np_time = time.time() - start_time

start_time = time.time()
x_sp = spla.solve(A, b) #matrix inverse
sp_time = time.time() - start_time

print(f"NumPy time: {np_time:.6f} seconds")
print(f"SciPy time: {sp_time:.6f} seconds")
print(f"Speed difference: {np_time / sp_time:.2f}x")

#SciPy Sparse 
print("\n---------SciPy Sparse---------")
from scipy import sparse 
dense_matrix = np.array([
    [1, 0, 2],
    [0, 3, 4],
    [5, 6, 0]
]); print("Dense Matrix:\n", dense_matrix)
csr_matrix = sparse.csr_matrix(dense_matrix)
print("CSR Matrix:\n", type(csr_matrix), csr_matrix)

from scipy.sparse import linalg as spla
A = sparse.csr_matrix([[1,2], [3,0]])
b = np.array([1, 2])
x = spla.spsolve(A, b)
print("Solution to Ax = b:\n", x)


---------Making use of namespaces---------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01+0.j -1.11684397e+00+0.j -1.30367773e-15+0.j]
[ 1.61168440e+01+0.j -1.11684397e+00+0.j -1.30367773e-15+0.j]
[ 1.61168440e+01+0.j -1.11684397e+00+0.j -1.30367773e-15+0.j]

---------SciPy Linear Algebra---------
NumPy time: 0.038074 seconds
SciPy time: 3.038791 seconds
Speed difference: 0.01x

---------SciPy Sparse---------
Dense Matrix:
 [[1 0 2]
 [0 3 4]
 [5 6 0]]
CSR Matrix:
 <class 'scipy.sparse._csr.csr_matrix'> <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (0, 2)	2
  (1, 1)	3
  (1, 2)	4
  (2, 0)	5
  (2, 1)	6
Solution to Ax = b:
 [0.66666667 0.16666667]
