### Week 6 Numpy Practice Problems (continued)

In [1]:
import numpy as np

### Problem 1 (revisit)
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [9]:
def add_border(x):
    return np.pad(x, 1, 'constant', constant_values=0)

In [11]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

In [13]:
# Let's go throught the document together
# The np.pad function in NumPy is versatile and can be used in various ways to add borders or padding to arrays
# 1) Number of values padded to the edges of each axis. ((before_1, after_1), ... (before_N, after_N)) 
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=0)
print(padded)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 0 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Pad with different mode 'constant' -> 'mode'
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='edge')
print(padded)

In [ ]:
# Pad with different values on each side
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=((5,6), (7,8)))
print(padded)

### Problem 2
Your task is to create a 2D array that shows the temperature for each city for each day of the week, assuming all cities have the same temperature pattern but with different baselines:

City 1: (first in the list): Use the temperatures as they are

City 2: Add  `5°C` to the temperatures

City 3: Subtract  `2°C` from the temperatures

In [49]:
def create_city_temperatures(temperatures, cities, offsets=None):
    """
    Create a 2D array (n_cities x n_days) of temperatures for multiple cities.
    All cities share the same daily pattern (temperatures) but have different baselines (offsets).

    Default offsets for 3 cities: [0, +5, -2].
    """
    if not offsets: 
        offsets = np.array([0, 5, -2])
    temperatures = temperatures.reshape(1,len(temperatures))
    offsets = offsets.reshape(len(cities),1)
    return temperatures + offsets

# def create_city_temperatures(temperatures, cities, offsets=None):
#     """
#     Create a 2D array (n_cities x n_days) of temperatures for multiple cities.
#     All cities share the same daily pattern (temperatures) but have different baselines (offsets).

#     Default offsets for 3 cities: [0, +5, -2].
#     """
#     temps = np.asarray(temperatures, dtype=float)  # ensure float for offsets
#     cities = np.asarray(cities)
#     n_cities = cities.shape[0]

#     if offsets is None:
#         # Default per prompt: City1 +0, City2 +5, City3 -2; extra cities get 0
#         offsets = np.zeros(n_cities, dtype=float)
#         if n_cities >= 2:
#             offsets[1] = 5.0
#         if n_cities >= 3:
#             offsets[2] = -2.0
#     else:
#         offsets = np.asarray(offsets, dtype=float)
#         if offsets.shape[0] != n_cities:
#             raise ValueError("offsets length must match number of cities")

#     # Broadcast: (n_cities, 1) + (1, n_days) -> (n_cities, n_days)
#     return offsets[:, np.newaxis] + temps[np.newaxis, :]

In [50]:
# Given data
temperatures = np.array([20, 22, 25, 19, 23, 21, 18])  # 7 days
cities = np.array(['New York', 'Los Angeles', 'Chicago'])
# Create and print the result
result = create_city_temperatures(temperatures, cities)
print(result)
# Print with city names
for i, city in enumerate(cities):
    print(f"\n{city}:")
    print(result[i, :])

[[20 22 25 19 23 21 18]
 [25 27 30 24 28 26 23]
 [18 20 23 17 21 19 16]]

New York:
[20 22 25 19 23 21 18]

Los Angeles:
[25 27 30 24 28 26 23]

Chicago:
[18 20 23 17 21 19 16]


### Additional Practice

In [2]:
## More on array manipulation 

# More on broadcasting 
    #np.newaxis and None are used to add a new dimension to an existing array 

#expanding vector dimensions using np.newaxis for compatibility
print("\nExpanding dimensions with np.newaxis:")
my_matrix = np.array([[1, 2, 3],
                       [4, 5, 6]]); print(my_matrix); print(my_matrix.shape) # (2,3)
my_vec = np.array([10, 20]); print(my_vec); print(my_vec.shape) # (2,)
my_vec = my_vec[:, np.newaxis]; print(my_vec); print(my_vec.shape) # (2,1)

print(my_matrix + my_vec) # (2,3) + (2,1) -> (2,3)

#expanding vector dimensions using None 
print("\nExpanding dimensions with None:")
my_matrix = np.array([[1, 2, 3],
                       [4, 5, 6]]); print(my_matrix); print(my_matrix.shape) # (2,3)
my_vec = np.array([10, 20]); print(my_vec); print(my_vec.shape) # (2,)
my_vec = my_vec[:, None]; print(my_vec); print(my_vec.shape) # (2,1)

print(my_matrix + my_vec) # (2,3) + (2,1) -> (2,3)



Expanding dimensions with np.newaxis:
[[1 2 3]
 [4 5 6]]
(2, 3)
[10 20]
(2,)
[[10]
 [20]]
(2, 1)
[[11 12 13]
 [24 25 26]]

Expanding dimensions with None:
[[1 2 3]
 [4 5 6]]
(2, 3)
[10 20]
(2,)
[[10]
 [20]]
(2, 1)
[[11 12 13]
 [24 25 26]]


In [3]:
# More on matrix/vector operations 

#* is elementwise multiplication for numpy.ndarray 
print("\nElementwise multiplication:")
A = np.reshape(np. arange(1,13), (3,4)); print(A); print(A.shape) # (3,4)
x = np.ones(4) * 2 ; print(x); print(x.shape) # (4,)
print(A * x) # (3,4) * (4,) -> (3,4)

#* is matrix multiplication for numpy.matrix
print("\nMatrix-Vector multiplication:")
A = np.matrix(np. arange(1,13)).reshape(3,4); print(A); print(A.shape) # (3,4)
x = np.ones((4,1)) * 2 ; print(x); print(x.shape) # (4,1)
print(A * x) # (3,4) * (4,1) -> (



Elementwise multiplication:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[2. 2. 2. 2.]
(4,)
[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]]

Matrix-Vector multiplication:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[2.]
 [2.]
 [2.]
 [2.]]
(4, 1)
[[20.]
 [52.]
 [84.]]


In [4]:
# More on matrix multiplication 
    # @ operator preferred 

#create two 2D NumPy arrays 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

#matrix multiplication using np.matmul()
print("Matrix multiplication using np.matmul():")
print(np.matmul(A, B))

#matrix multiplication using @ operator
print("Matrix multiplication using @ operator:")
print(A @ B)

Matrix multiplication using np.matmul():
[[ 58  64]
 [139 154]]
Matrix multiplication using @ operator:
[[ 58  64]
 [139 154]]


In [8]:
# Array Stack 
a = np.array([[1,2],[3,4]], dtype = 'uint'); print(a)
b = np.array([[5,6],[7,8]], dtype = 'uint'); print(b)
print("----------- Vertical Stack -----------\n")
print(np.vstack((a, b)))
print("----------- Horizontal Stack -----------\n")
print(np.hstack((a, b)))
print("----------- Concatenate Vertical -----------\n")
print(np.concatenate((a,b), axis=0)) # vertical stack
print("----------- Concatenate Horizontal -----------\n")
print(np.concatenate((a,b), axis=1)) # horizontal stack

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
----------- Vertical Stack -----------

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------- Horizontal Stack -----------

[[1 2 5 6]
 [3 4 7 8]]
----------- Concatenate Vertical -----------

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------- Concatenate Horizontal -----------

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
# Universal functions (ufuncs) practice 
x1 = np.array([10, 20, 30]); print(x1) 
x2 = np.array([3, 4, 5]); print(x2)

#using np.divmod() 
print("\n---------------Using np.divmod():---------\n")
result_array = np.divmod(x1, x2)
print(result_array)

# regular python lists 
list1 = [10, 20, 30]
list2 = [3, 4, 5]
print("\n---------------Using map() with divmod():---------\n")
print(list(map(divmod, list1, list2))) #not as efficient as np.divmod() in numpy 


[10 20 30]
[3 4 5]

---------------Using np.divmod():---------

(array([3, 5, 6]), array([1, 0, 0]))

---------------Using map() with divmod():---------

[(3, 1), (5, 0), (6, 0)]


In [6]:
# Statistics in NumpPy
die_rolls = np.random.randint(1, 7, size=10); print(die_rolls)
errors = np.random.normal(loc=0.0, scale = 1.0, size=10); print(errors)
print(np.mean(die_rolls))
print(np.std(die_rolls))
print(np.percentile(die_rolls, 25))


[3 5 3 4 2 2 3 1 3 5]
[ 0.01058139  0.9314971   1.45124135  1.00659728 -0.15850992  0.08161408
  1.15108423 -0.24548389 -1.12562694 -1.97773499]
3.1
1.2206555615733703
2.25


In [7]:
# Random numbers in NumPy 
print(np.random.random((2,3)))
print(np.random.normal(0,1,20))
print(np.random.uniform(0,1,(2,4)))

[[0.07888779 0.78368994 0.56346425]
 [0.03885747 0.6182649  0.60347435]]
[-0.20417847  1.00714599 -0.17794243 -0.91970855 -0.48158989 -0.02841792
  1.13287947  1.34557788  0.30706204 -0.37140759 -1.26306483  0.25461864
  0.05903733  1.10475993  0.24768079  0.17504337 -0.18283881  0.09591805
  1.01972573  0.73738955]
[[0.94786196 0.32070013 0.38297009 0.04638059]
 [0.04424293 0.9833422  0.44225902 0.11928743]]


In [8]:
# Sampling from data 
x = np.arange(1,11)
for i in range(5): 
    print(np.random.choice(x,5,False,x/float(sum(x))))

[8 4 2 3 9]
[10  2  8  9  3]
[2 9 5 6 8]
[10  7  9  3  5]
[ 8 10  9  5  3]


In [9]:
# shuffle() vs permutation()
x = np.arange(10); print(x)
np.random.shuffle(x); print(x) # shuffles x in place

y = np.arange(10); print(y)
z = np.random.permutation(y); print(z) # returns a shuffled copy of y,

[0 1 2 3 4 5 6 7 8 9]
[5 8 0 1 4 9 2 3 6 7]
[0 1 2 3 4 5 6 7 8 9]
[1 2 0 6 8 3 4 9 5 7]


In [10]:
# NaNs in NumPy 
x = np.array([1, 2, np.nan, 4, 5, np.nan])
print(np.isnan(x))
print(np.nanmean(x))  # mean ignoring NaNs
print(np.nanstd(x))   # std dev ignoring NaNs

[False False  True False False  True]
3.0
1.5811388300841898


In [11]:
# Probability and statistics in SciPy 
import scipy.stats 
x = np.random.normal(0,1,20)
result = scipy.stats.kstest(x, 'norm') # Kolmogorov-Smirnov test for normality