### Week 6-1 NumPy Practice Problems

In [2]:
import numpy as np

### Warm up
NumPy creation and indexing.

In [25]:
# 1. Creates 3x3 array of zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# 2. Creates array [0, 2, 4, 6, 8]
np.array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

In [33]:
# 3. 5 evenly spaced numbers from 0 to 1
print(np.arange(0, 1.1, 0.25))
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


In [34]:
# Array indexing, Gets elements > 5
arr = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(arr[arr > 5])

[6 7 8 9]


### Problem 1
Convert an array of Celsius measurements to Fahrenheit.
Note: `fahrenheit = (Celsius * 9/5) + 32`.

In [ ]:
def convert_to_fahrenheit_list(temperatures):
    '''Convert an array of Celsius temperatures to Fahrenheit measurements
        Input: list of temperatures in Celsius
    '''
    return [temp * 9/5 + 32 for temp in temperatures]

In [36]:
print("Testing with a regular list:")
temps_list = [0, 10, 20, 30]
print(convert_to_fahrenheit_list(temps_list))

Testing with a regular list:
[32.0, 50.0, 68.0, 86.0]


In [ ]:
def convert_to_fahrenheit_numpy_array(temperatures):
    '''Convert an array of Celsius temperatures to Fahrenheit measurements
        Input: numpy array of temperatures in Celsius
    '''
    # element-wise operations
    return temperatures * 9/5 + 32

In [39]:
print("\nTesting with a NumPy array:")
temps_array = np.array([0, 10, 20, 30])
print(convert_to_fahrenheit_numpy_array(temps_array))


Testing with a NumPy array:
[32. 50. 68. 86.]


### Problem 2
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [ ]:
# help(np.pad)
def add_border(x):
    '''Add a border of zeros around a 2D numpy array
        Input: 2D numpy array
        Output: 2D numpy array with border of zeros
    '''
    return np.pad(x, pad_width=1, mode='constant', constant_values=0)

def add_border(x):
#     '''Add a border of zeros around a 2D numpy array
#         Input: 2D numpy array
#         Output: 2D numpy array with border of zeros
#     '''
#     # Get the shape of the original array
#     rows, cols = x.shape
    
#     # Create a new array with an extra row and column on each side
#     bordered_array = np.zeros((rows + 2, cols + 2), dtype=x.dtype)
    
#     # Place the original array in the center of the new array
#     bordered_array[1:-1, 1:-1] = x
    
#     return bordered_array

In [50]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
print("\nTesting add_border function:")
print("Claimed result:\n", claimed)
print("Correct result:\n", correct)


Testing add_border function:
Claimed result:
 [[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Correct result:
 [[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [51]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

### Problem 3
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [ ]:
# def make_checkerboard(n):
#     '''Create an n x n checkerboard pattern
#         Input: integer n
#         Output: n x n numpy array with checkerboard pattern
#     '''
#     checkerboard = np.zeros((n, n), dtype=int)
#     checkerboard[1::2, ::2] = 1  # Fill 1s in odd rows, even columns
#     checkerboard[::2, 1::2] = 1  # Fill 1s in even rows, odd columns
#     return checkerboard

def make_checkerboard(n):
    '''Create an n x n checkerboard pattern
        Input: integer n
        Output: n x n numpy array with checkerboard pattern
    '''
    row = np.arange(n); row = row[:, np.newaxis]
    col = np.arange(n).reshape(1,n)
    res = row + col
    checkerboard = (res % 2).astype(int)
    return checkerboard

In [60]:
make_checkerboard(8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [55]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

### Additional Practice 

In [4]:
## NumPy as numerical computing (Basics)

# Numpy data types 
print("-------Numpy data types-------")
x = np.float32(3.1415); print(type(x))
x = np.int32(8); print(type(x))
x = np.float64(2.71828); print(type(x))

x = np.float16(3.1415); y = np.float64(3.1415)
print(x == y) #False # due to precision loss in float16

#data type followed by underscore uses default number of bits 
x = np.int_(8); print(type(x)) # int32 or int64 depending on platform

# Creating NumPy array 
print("\n-------Creating NumPy array-------")
#from a list 
arr1 = np.array([1,2,3,4,5], dtype = 'uint'); print(type(arr1))

#from a tuple 
arr2 = np.array((1,2,3,4,5), dtype = 'uint'); print(type(arr2))

# Using NumPy array functions - 1D 
print("\n-------Using NumPy array functions - 1D-------")
#create an array of zeros 
zeros_arr = np.zeros(5); print(zeros_arr)

# create an array of ones 
ones_2d = np.ones((2,3)); print(ones_2d)

#create an array with a range of values 
range_arr = np.arange(0,10,2); print(range_arr) # start, stop, step

#create an array with evenly spaced values 
linspace_arr = np.linspace(0,1,5); print(linspace_arr) # start, end, num of elements 

# Using NumPy array functions - 2D 
print("-------Using NumPy array functions - 2D-------")
#2D identity matrices 
print(np.eye(3))
print(np.eye(3,5))

#2D square matrices with diagonal terms 
np.diag([1,2,3])

# Create NumPy array based on the properties of existing arrays 
print("\n-------Create NumPy array based on the properties of existing arrays -------")
#create sample array
sample = np.array([[1,2,3],[4,5,6]]); print(sample)

#create new array with same shape as sample, filled with 7
full_like_arr = np.full_like(sample,7); print(full_like_arr)

#can be replaced with ones instead 
zeros_like_arr = np.zeros_like(sample); print(zeros_like_arr)

# NumPy arrays attributes
print("\n-------NumPy arrays attributes -------")
b = np.arange(10).reshape(2,5); print(b)

#get array attributes
print(b.ndim) #number of dimensions
print(b.shape)
print(b.dtype) #data type
print(b.size) #total number of elements


-------Numpy data types-------
<class 'numpy.float32'>
<class 'numpy.int32'>
<class 'numpy.float64'>
False
<class 'numpy.int64'>

-------Creating NumPy array-------
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

-------Using NumPy array functions - 1D-------
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
-------Using NumPy array functions - 2D-------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

-------Create NumPy array based on the properties of existing arrays -------
[[1 2 3]
 [4 5 6]]
[[7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]

-------NumPy arrays attributes -------
[[0 1 2 3 4]
 [5 6 7 8 9]]
2
(2, 5)
int64
10


In [16]:
## Array indexing 

#slicing 
print("------- Slicing---------")
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]); print(a)
b = a[:2, 1:3]; print(b)

#integer array indexing 
print("------- Integer array indexing-------")
a = np.array([[1,2], [3, 4], [5, 6]]); print(a)
print(a[[0,1,2], [0,1,0]]) #prints "[1 4 5]"
print(np.array([a[0,0], a[1,1], a[2,0]])) #equivalent to above

#boolean array indexing
print("-------Boolean array indexing-------")
print(a)
bool_idx = (a > 2); print(bool_idx) # Find the elements of a that are bigger than 2; this returns a boolean array
print(a[a > 2]) # prints "[3 4 5 6]", which are the elements of a where the condition is True

#Boolean operations: np.all() and np.any()
print("------- Boolean operations-------")
x = np.arange(10); print(x)
print(np.all(x > 7)) #False
print(np.any(x > 7)) #True
print(np.any((x>7, x < 2))) #True
print(np.any([x>7, x<2], axis=1)) #row-wise
print(np.any([x>7, x<2], axis=0)) #desired entrywise behavior; column-wise

#np.logical_and(), np.logical_or(), np.logical_not()
print("------- Logical operations-------")
x = np.arange(10);  print(x)
print(x[np.logical_and(x>3, x<7)])
print(np.logical_or(x<3, x>7))
print(x[np.logical_or(x<3, x>7)])
print(x[np.logical_xor(x<3, x>7)]) #elements that are either <3 or >7 but not both
print(x[np.logical_not(x<5)]) #elements that are not <5; equivalent to x[x>=5]

------- Slicing---------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
------- Integer array indexing-------
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
-------Boolean array indexing-------
[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
------- Boolean operations-------
[0 1 2 3 4 5 6 7 8 9]
False
True
True
[ True  True]
[ True  True False False False False False False  True  True]
------- Logical operations-------
[0 1 2 3 4 5 6 7 8 9]
[4 5 6]
[ True  True  True False False False False False  True  True]
[0 1 2 8 9]
[0 1 2 8 9]
[5 6 7 8 9]


In [5]:
## Math, Vector and Matrix Operations 

#Array math 
x = np.array([[1,2],[3,4]], dtype=np.float64); print(x)
y = np.array([[5,6],[7,8]], dtype = np.float64); print(y)

#elementwise sum
print("----------------- \n Elementwise sum")
print(x + y); print(np.add(x,y))

#elementwise difference 
print("----------------- \n Elementwise difference")
print(x - y); print(np.subtract(x,y))

#elementwise product 
print("----------------- \n Elementwise product")
print(x * y); print(np.multiply(x,y))

#elementwise division
print("----------------- \n Elementwise division")
print(x / y); print(np.divide(x,y))

#elementwise square root
print("----------------- \n Elementwise square root")
print(np.sqrt(x)); print(np.sqrt(y))



[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
----------------- 
 Elementwise sum
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
----------------- 
 Elementwise difference
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
----------------- 
 Elementwise product
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
----------------- 
 Elementwise division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----------------- 
 Elementwise square root
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [6]:
# Array axis 
x = np.array([[1,2], [3,4]]); print(x)
print("----------------- \n Column-wise sum")
print(np.sum(x, axis=0))

print("----------------- \n Row-wise sum")
print(np.sum(x, axis=1))

print("----------------- \n sum of all elements")
print(np.sum(x))

[[1 2]
 [3 4]]
----------------- 
 Column-wise sum
[4 6]
----------------- 
 Row-wise sum
[3 7]
----------------- 
 sum of all elements
10


In [19]:
# Vector operations in NumPy 
print("\n-------Vector and Matrix Operations -------")
x = np.array([[1,2], [3,4]]); print(x)
y = np.array([[5,6], [7,8]]); print(y)
v = np.array([9,10]); print(v)
w = np.array([11, 12]); print(w)

#inner product 
print("----------------- \n Inner product")
print(v.dot(w)); print(np.dot(v,w))

#matrix-vector product 
print(x.dot(v)); print(np.dot(x,v))

#matrix-matrix product
print(x.dot(y)); print(np.dot(x,y))


-------Vector and Matrix Operations -------
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
----------------- 
 Inner product
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
## (Array) broadcasting
    # dimensions compatible for broadcasting if:
        #1. they are equal, or
        #2. one of them is 1

#both a and b with shape (4,3)
print("----------------- \n Both a and b with shape (4,3)")
a = np.array([[0,0,0], 
             [10,10,10], 
             [20,20,20], 
             [30,30,30]])
b = np.array([[0,1,2], 
             [0,1,2], 
             [0,1,2], 
             [0,1,2]])
print(a + b)

#a: (4,3), b: (1,3)
print("----------------- \n a: (4,3), b: (1,3)")
a = np.array([[0,0,0], 
             [10,10,10], 
             [20,20,20], 
             [30,30,30]])
b = np.array([[0,1,2]])
print(a + b)

#a: (4,1), b: (1,3)
print("----------------- \n a: (4,1), b: (1,3)")
a = np.array([[0], 
             [10], 
             [20], 
             [30]])
b = np.array([[0,1,2]])
print(a + b)

----------------- 
 Both a and b with shape (4,3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
----------------- 
 a: (4,3), b: (1,3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
----------------- 
 a: (4,1), b: (1,3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
